version: '3'

services:

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../proxy/conf.d:/etc/nginx/conf.d
      - ../../proxy/vhost.d:/etc/nginx/vhost.d
      - ../../proxy/html:/usr/share/nginx/html
      - ../../proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./my_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf
    networks:
      - proxy-tier 
    restart: unless-stopped 

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - proxy
    volumes:
      - ../../proxy/conf.d:/etc/nginx/conf.d
      - ../../proxy/vhost.d:/etc/nginx/vhost.d
      - ../../proxy/html:/usr/share/nginx/html
      - ../../proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped 

networks:
  proxy-tier:
    external:
      name: nginx-proxy
