# Need to be configured with:
# DOMAIN_NEXTCLOUD:
#   Domain name of the nextcloud
#   ex: nextcloud.mydomain.com,nextcloud.mydomain2.com
# EMAIL_NEXTCLOUD:
#   Mail for SSL encryption
#   ex: myemail@mail.com
# MARIA_ROOT_PASSWORD:
#   Root password for mariadb
#   ex: my_s3cret
# MARIA_DB_PASSWORD:
#   DB password for mariadb
#   ex: my_s3cret
# DOMAIN_NEXTCLOUD_WITH_DOUBLE_BACKSLASH:
#   domain accepted by collabora
#   ex: nextcloud\\.mydomain\\.com

version: '3'

services:

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../nextcloud/html:/var/www/html:ro
    links:
      - nextcloud-fpm
      - collab
    environment:
      - VIRTUAL_HOST=DOMAIN_NEXTCLOUD
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=DOMAIN_NEXTCLOUD
      - LETSENCRYPT_EMAIL=EMAIL_NEXTCLOUD
    networks:
      - proxy-tier
    restart: unless-stopped

  nextcloud-fpm:
    image: nextcloud:fpm
    container_name: nextcloud-fpm
    links:
      - db
      - redis
    volumes:
      - ../../nextcloud/html:/var/www/html
    networks:
      - proxy-tier
    restart: unless-stopped

  db:
    image: mariadb
    container_name: db
    volumes:
      - ../../nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MARIA_ROOT_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=MARIA_DB_PASSWORD
    networks:
      - proxy-tier
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ../../nextcloud/redis:/data
    networks:
      - proxy-tier
    restart: unless-stopped

  collab:
    image: collabora/code
    container_name: collab
    environment:
      - 'domain=DOMAIN_NEXTCLOUD_WITH_DOUBLE_BACKSLASH'
    cap_add:
      - MKNOD
    networks:
      - proxy-tier
    restart: unless-stopped

networks:
  proxy-tier:
    external:
      name: nginx-proxy
